### ISSUE TITLE
Incorrect example configuration for Amazon Elasticsearch output

### ISSUE THREAD

**Issue by metroshica** [banzaicloud/logging-operator-docs#65]
**Describe the bug**
The example configuration for the [Amazon Elatsearch output](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/aws_elasticsearch/#example-output-configurations) is incorrect. It appears that it was copied from the [Amazon Kinesis Stream](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/kinesis_stream/#example-output-configurations) documentation.

**Steps to reproduce the issue:**
Read example output configuration for Amazon Elasticsearch output plugin:
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/aws_elasticsearch/#example-output-configurations

**Expected behavior**
Example configuration should be for Amazon Elaticsearch, not Amazon Kinesis Stream.

**Screenshots**
![image](https://user-images.githubusercontent.com/7684916/111698284-07198f00-880d-11eb-860d-cef303555ab6.png)

**Comment by fekete-robert** [comment]
Hi, thanks a lot for the report, I'll ask the guys for a correct example.

**Comment by jadhavnitind** [comment]
It's been 1.6 years and the document is still not updated. Is there anyone who is going to update the document?

**Comment by fekete-robert** [comment]
Sorry, this fell between the cracks.
Try something like:

```yaml
spec:
  awsElasticsearch:
    logstash_format: true
    include_tag_key: true
    tag_key: "@log_name"
    flush_interval: 1s
    endpoint:
      url: https://CLUSTER_ENDPOINT_URL
      region: eu-west-1
      access_key_id:
        value: aws-key
      secret_access_key:
        value: aws_secret
```

I'll add it to the docs as well
